# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: use node.js 12
        uses: actions/setup-node@v1
        with:
          version: 12

      # install
      - name: npm install
        run: npm install

      # Lint
      - name: lint
        run: npm run lint

      # E2E
      - name: e2e
        uses: cypress-io/github-action@v2.6.1
        with:
          headless: true
          # Provide a specific specs to run
          # spec: google.spec.ts
          # Whether or not to silence any Cypress specific output from stdout
          quiet: false
